<?php
/**
 * Flipbook Plugin - Configuration Template
 *
 * This file will be copied to src/config.php during installation
 * DO NOT edit this file directly - it's a template
 */

// Database connection settings
define('FLIPBOOK_DB_HOST', '{{DB_HOST}}');
define('FLIPBOOK_DB_NAME', '{{DB_NAME}}');
define('FLIPBOOK_DB_USER', '{{DB_USER}}');
define('FLIPBOOK_DB_PASS', '{{DB_PASS}}');
define('FLIPBOOK_DB_CHARSET', 'utf8mb4');

// Table prefix (allows multiple instances in same database)
define('FLIPBOOK_TABLE_PREFIX', '{{TABLE_PREFIX}}');

// Application settings
define('FLIPBOOK_UPLOAD_DIR', '{{UPLOAD_DIR}}');
define('FLIPBOOK_MAX_FILE_SIZE', 50 * 1024 * 1024); // 50MB in bytes
define('FLIPBOOK_ALLOWED_PDF_TYPES', ['application/pdf']);
define('FLIPBOOK_ALLOWED_AUDIO_TYPES', ['audio/mpeg', 'audio/mp3']);

// Admin credentials (change these!)
define('FLIPBOOK_ADMIN_USER', '{{ADMIN_USER}}');
define('FLIPBOOK_ADMIN_PASS', '{{ADMIN_PASS}}'); // Will be hashed

// Security settings
define('FLIPBOOK_SESSION_NAME', 'flipbook_admin_session');
define('FLIPBOOK_SESSION_TIMEOUT', 3600); // 1 hour in seconds

// Application paths
define('FLIPBOOK_BASE_PATH', __DIR__ . '/..');
define('FLIPBOOK_SRC_PATH', FLIPBOOK_BASE_PATH . '/src');

// Error reporting (set to 0 in production)
define('FLIPBOOK_DEBUG', {{DEBUG}});

if (FLIPBOOK_DEBUG) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}
?>
